
import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';
import pluginUnicorn from 'eslint-plugin-unicorn';
import astroPlugin from 'eslint-plugin-astro';

export default [
    {
        ignores: [
            "dist/",
            ".history/",
            "node_modules/",
            ".cache/",
            ".astro/",
            "**/*.min.js",
            "**/plugins/",
            "/.temp/",
            "source/html/docs/",
            "docs_html/",
            "public/",
            "www/",
            "ios",
            "android",
            "capacitor-assets/",
        ],
    },
    ...tseslint.config(
        pluginJs.configs.recommended,
        ...tseslint.configs.recommended,
    ),
    {
        ...pluginUnicorn.configs['flat/recommended'],
    },
    ...astroPlugin.configs['flat/recommended'],
    {
        files: ['**/*.{js,mjs,cjs,ts,mts,cts,astro}'],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
            },
        },
        rules: {
            'comment-whitespace-inside': 'off',
            'arrow-body-style': 'off',
            'capitalized-comments': 'off',
            'comma-dangle': ['warn', 'always-multiline'],
            'indent': ['off', 4, { 'MemberExpression': 'off', 'SwitchCase': 1 }],
            'max-params': ['warn', 5],
            'multiline-ternary': 'off',
            'new-cap': 'off',
            'no-console': 'off',
            'no-negated-condition': 'off',
            'object-curly-spacing': ['warn', 'never'],
            'operator-linebreak': ['warn', 'after'],
            'no-unused-vars': 'off',
            'no-new': 'off',
            'semi': 'off',
            'no-empty': 'warn',
            'unicorn/explicit-length-check': 'off',
            'unicorn/no-array-callback-reference': 'off',
            'unicorn/no-array-for-each': 'off',
            'unicorn/no-array-method-this-argument': 'off',
            'unicorn/no-null': 'off',
            'unicorn/no-unused-properties': 'off',
            'unicorn/prefer-array-flat': 'off',
            'unicorn/prefer-dom-node-dataset': 'off',
            'unicorn/prefer-export-from': 'off',
            'unicorn/prefer-module': 'off',
            'unicorn/prefer-query-selector': 'off',
            'unicorn/prefer-spread': 'off',
            'unicorn/prefer-string-replace-all': 'off',
            'unicorn/prevent-abbreviations': 'off',
            'astro/no-set-html-directive': 'off',
            'unicorn/filename-case': 'off',
            '@typescript-eslint/no-unused-vars': 'off',
            '@typescript-eslint/no-explicit-any': 'warn',
            'unicorn/prefer-global-this': 'off',
            'unicorn/prefer-top-level-await': 'off',
            'unicorn/prefer-ternary': 'off',
            'unicorn/prefer-switch': 'warn',
            'unicorn/import-style': 'warn',
            'unicorn/text-encoding-identifier-case': 'warn',
            'unicorn/prefer-add-event-listener': 'warn',
            'unicorn/catch-error-name': 'warn',
            'unicorn/no-process-exit': 'warn',
            'unicorn/prefer-classlist-toggle': 'warn',
            'unicorn/consistent-function-scoping': 'warn',
            'unicorn/prefer-dom-node-append': 'warn',
            'unicorn/no-array-sort': 'warn',
            'unicorn/no-useless-undefined': 'warn',
            '@typescript-eslint/no-unused-expressions': 'warn',
            'unicorn/switch-case-braces': 'warn',
            'unicorn/empty-brace-spaces': 'warn',
            'unicorn/no-nested-ternary': 'warn',
            'unicorn/no-negated-condition': 'warn',
            'unicorn/prefer-at': 'warn',
            'unicorn/no-array-reduce': 'warn',
            'unicorn/prefer-math-min-max': 'warn',
            'no-cond-assign': 'warn',
            'no-undef': 'warn',
            'unicorn/prefer-optional-catch-binding': 'warn',
            'no-prototype-builtins': 'warn',
            'unicorn/prefer-includes': 'warn',
            'object-curly-spacing': 'warn',
            'unicorn/prefer-native-coercion-functions': 'warn',
            'unicorn/no-new-array': 'warn',
            'comma-dangle': 'warn',
            'operator-linebreak': 'warn',
            'multiline-ternary': 'warn',
            'no-dupe-keys': 'warn',

        },
    },
    {
        files: ['source/config/**'],
        languageOptions: {
            globals: {
                ...globals.node,
            },
        },
        rules: {
            'no-console': 'off',
            'unicorn/prefer-top-level-await': 'off',
        },
    },
] 